### ISSUE TITLE
Loggin to trystack.

### ISSUE THREAD

**Issue by Clp4tp** [gondor/openstack4j#191]
Hello,
I am new to cloud computing and I am trying to connect to trystack in order to use some of its features. I have downloaded all jar's with the dependencies and i am currently using the example provided to connect to trystack and this is the error i am getting:
<code>Exception in thread "main" java.lang.NullPointerException
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:78)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:41)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:84)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:65)
	at com.jim.netbeanscloud2.Connection.main(Connection.java:20)</code>

I am running the project with NetBeans and Maven also gives an error:
<code>BUILD FAILURE
Total time: 2.917s
Finished at: Mon Jan 05 15:56:38 EET 2015
Final Memory: 6M/153M
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project NetbeansCloud2: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.
For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException</code>

The code responsible for the connection is the following:
<code>OSClient os = OSFactory.builder()
            .endpoint("https://x86.trystack.org/dashboard")
            .credentials("myUsernameProvidedFromTrystack","myPass")
            .tenantName("myUsernameProvidedFromTrystack")
            .authenticate();</code>

Since i am new to cloud computing i don't know what i am doing wrong.Both ways of connecting(V2&V3) provided fail to connect...

**Comment by magixyu** [comment]
I guess the URL in the endpoint part should be the AUTH_URL but not the dashboard URL. Please try to update it and re-test.
.endpoint("https://x86.trystack.org/dashboard")

**Comment by Clp4tp** [comment]
Thank you for the fast reply!
 I changed the URL as prompted to <code> .endpoint("https://x86.trystack.org/dashboard/auth/login/")</code> but the error remains the same.
I also tried to connect using builderV3 but i have no idea what the <code>.domainName("example-domain")</code> should be...
Also, do I need a server to connect? Or jersey is responsible for this?
This is my pom.xml:
 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.jim</groupId>
    <artifactId>NetbeansCloud2</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>
    <dependencies>
		<dependency>
			<groupId>org.pacesys</groupId>
			<artifactId>openstack4j</artifactId>
			<version>2.0.0</version>
			<classifier>withdeps</classifier>
		</dependency>
		<dependency>
			<groupId>org.pacesys.openstack4j.connectors</groupId>
			<artifactId>openstack4j-jersey2</artifactId>
			<version>2.0.0</version>
		</dependency>
	</dependencies>
</project>

**Comment by gondor** [comment]
All the URLs you have posted look invalid.  Typically the auth URL endpoint should end in like a /v2.0.  Like https://hostname:5000/v2.0

**Comment by Clp4tp** [comment]
That is true, yet at TryStack they don't provide an auth URL like the one in  the sample.
 This client can connect to the devstack setup I have locally. But not at Trystack.

**Comment by gondor** [comment]
Have you tried using the CLI commands to manage TryStack?  Typically if your using that then you could look at your terminals environment variables and should find the URL in there.

**Comment by Clp4tp** [comment]
I'll look into that!Thanks a lot!
