### ISSUE TITLE
Connect openstack server remotely using ssh tunnel time out due to endpoint changes

### ISSUE THREAD

**Issue by pokocat** [gondor/openstack4j#192]
Hi,
I'm using Openstack4j to connect remote openstack server which needs to be routed via ssh tunnel.
For example, I've to identify using 127.0.0.1:5000/v2.0, and then the response json gives a compute endpoint with remote internal ip address e.g. 192.168.10.10:8774. Then openstack4j will use this address to connect, which of course will be time out. 
Is this condition will be considered as a problem?

[2015-01-06 11:08:38,446|DEBUG|]: Authenticate with OS server of: {URL:http://127.0.0.1:5000/v2.0,User:admin,Password:admin,Tenent:admin}
[2015-01-06 11:08:39,311|DEBUG|http.wire]: http-outgoing-0 >> "POST /v2.0/tokens HTTP/1.1[\r][\n]"
[2015-01-06 11:08:39,311|DEBUG|http.wire]: http-outgoing-0 >> "OS4J-Auth-Command: Tokens[\r][\n]"
[2015-01-06 11:08:39,312|DEBUG|http.wire]: http-outgoing-0 >> "  "auth" : {[\r][\n]"
[2015-01-06 11:08:39,312|DEBUG|http.wire]: http-outgoing-0 >> "    "tenantName" : "admin",[\r][\n]"
[2015-01-06 11:08:39,312|DEBUG|http.wire]: http-outgoing-0 >> "    "passwordCredentials" : {[\r][\n]"
[2015-01-06 11:08:39,312|DEBUG|http.wire]: http-outgoing-0 >> "      "username" : "admin",[\r][\n]"
[2015-01-06 11:08:39,313|DEBUG|http.wire]: http-outgoing-0 >> "      "password" : "admin"[\r][\n]"
[2015-01-06 11:08:39,313|DEBUG|http.wire]: http-outgoing-0 >> "    }[\r][\n]"
[2015-01-06 11:08:39,313|DEBUG|http.wire]: http-outgoing-0 >> "  }[\r][\n]"
[2015-01-06 11:08:39,313|DEBUG|http.wire]: http-outgoing-0 >> "}"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "Vary: X-Auth-Token[\r][\n]"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "Content-Type: application/json[\r][\n]"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "Content-Length: 10122[\r][\n]"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "Date: Tue, 06 Jan 2015 02:58:48 GMT[\r][\n]"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "Connection: keep-alive[\r][\n]"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "[\r][\n]"
[2015-01-06 11:08:39,463|DEBUG|http.wire]: http-outgoing-0 << "{"access": {"token": {"issued_at": "2015-01-06T02:58:48.482479", "expires": "2015-01-06T03:58:48Z", "id": "id"//id omitted
[2015-01-06 11:08:39,469|DEBUG|http.headers]: http-outgoing-0 << HTTP/1.1 200 OK
[2015-01-06 11:08:39,469|DEBUG|http.headers]: http-outgoing-0 << Vary: X-Auth-Token
[2015-01-06 11:08:39,469|DEBUG|http.headers]: http-outgoing-0 << Content-Type: application/json
[2015-01-06 11:08:39,469|DEBUG|http.headers]: http-outgoing-0 << Content-Length: 10122
[2015-01-06 11:08:39,469|DEBUG|http.headers]: http-outgoing-0 << Date: Tue, 06 Jan 2015 02:58:48 GMT
[2015-01-06 11:08:39,469|DEBUG|http.headers]: http-outgoing-0 << Connection: keep-alive
[2015-01-06 11:08:39,478|DEBUG|execchain.MainClientExec]: Connection can be kept alive indefinitely

[2015-01-06 11:08:39,696|DEBUG|conn.PoolingHttpClientConnectionManager]: Connection [id: 0][route: {}->http://127.0.0.1:5000] can be kept alive indefinitely
[2015-01-06 11:08:39,697|DEBUG|conn.PoolingHttpClientConnectionManager]: Connection released: [id: 0][route: {}->http://127.0.0.1:5000][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]

[2015-01-06 11:08:39,810|DEBUG|execchain.MainClientExec]: Opening connection {}->http://192.168.0.25:8774
[2015-01-06 11:08:39,810|DEBUG|conn.HttpClientConnectionManager]: Connecting to /192.168.0.25:8774
[2015-01-06 11:09:00,806|DEBUG|conn.DefaultManagedHttpClientConnection]: http-outgoing-1: Shutdown connection
[2015-01-06 11:09:00,806|DEBUG|execchain.MainClientExec]: Connection discarded
[2015-01-06 11:09:00,806|DEBUG|conn.DefaultManagedHttpClientConnection]: http-outgoing-1: Close connection
[2015-01-06 11:09:00,806|DEBUG|conn.PoolingHttpClientConnectionManager]: Connection released: [id: 1][route: {}->http://192.168.0.25:8774][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
ConnectionException{message=Connect to 192.168.0.25:8774 [/192.168.0.25] failed: Connection timed out: connect, status=0}
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:55)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.0.25:8774 [/192.168.0.25] failed: Connection timed out: connect
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
	... 30 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	... 42 more

**Comment by gondor** [comment]
The behavior your describing is correct since we need to "trust" the endpoints OpenStack sends back in the authentication sequence. Some users may have different endpoints, etc.  

However, I have added support for all scenarios including NAT/Tunnels, etc.  

Try this.. (I'm assuming you want to keep using the 127.0.0.1 address).  Just note that the ports need to be tunneled as well (8774, etc) since each OpenStack service in your deployment will listen on a different port. 

```java
OSClient client = OSFactory.builder()
                .endpoint("http://127.0.0.1:5000/v2.0")
                .credentials("user", "example")
                .tenantName("tenant_example")
                .withConfig(Config.newConfig().withEndpointNATResolution("127.0.0.1")) // this option
                .authenticate();
```

**Comment by gondor** [comment]
@pokocat Closing due to no response.  Will re-open if you still can't figure things out based on my suggestions.

**Comment by pokocat** [comment]
Thanks Gondor, that's exactly what I needed. I tried to add the alternative NAT ip addr like you proposed and it worked like a charm! Sorry for the late response.

**Comment by AjinkyaR** [comment]
Hi Gondor,
We are facing similar scenario over here. We are trying to access the openstack from one domain (Domain A) to another domain (Domain B), both are accessible from each other.

We tried with the solution suggested by you but still its giving ConnectionTimeout Exception. Let me know if you need any specific details to resolve this.
