### ISSUE TITLE
 Adding users to role error

### ISSUE THREAD

**Issue by benxiaohai1212** [gondor/openstack4j#195]
ConnectionException{message=Error during execution: java.lang.IllegalStateException: Entity must not be null for http method PUT., status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:39)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:159)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:154)
	at org.openstack4j.openstack.identity.internal.RoleServiceImpl.addRemoveRoles(RoleServiceImpl.java:67)
	at org.openstack4j.openstack.identity.internal.RoleServiceImpl.addUserRole(RoleServiceImpl.java:35)
	at com.chinaops.openstack.TenantTest.main(TenantTest.java:79)
Caused by: java.lang.IllegalStateException: Entity must not be null for http method PUT.

Thank you!

**Comment by gondor** [comment]
What version of OpenStack4j are you using?

**Comment by benxiaohai1212** [comment]
Problem is all right ! thank you !
