### ISSUE TITLE
List servers in another thread

### ISSUE THREAD

**Issue by kaaas** [gondor/openstack4j#202]
Hello,

Authenticating against keystone and afterwards issuing other operations from another thread seems to produce exceptions.

public class InstanceTask extends TimerTask {
	private OSClient os;
	public InstanceTask(OSClient os) {
		this.os = os;
	}
	@Override
	public void run() {
		os.compute().servers().list();
        }
}

Following throws an NPE:

public static void main(String[] args) {
	OSclient os = ... //authenticate against keystone
	Timer timer = new Timer();
	timer.schedule(new Task(os), 1000, 60000)
}

and following does not:

public static void main(String[] args) {
	OSclient os = ... //authenticate against keystone
	new Task(os).run();
}

Heres the Stacktrace:

Exception in thread "Timer-0" java.lang.NullPointerException
	at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:84)
	at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:79)
	at org.openstack4j.openstack.internal.BaseOpenStackService.get(BaseOpenStackService.java:46)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:86)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:74)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:66)
	at de.uks.openstack.dnsaas.InstanceTask.run(InstanceTask.java:29)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by gondor** [comment]
You must create a new client in the new thread.  You don't need to re-authenticate if you pass-thru the access object from the original authentication.  Some people cache the Access object and threads pull it from the cache.  Many ways..  Simple example is documented on OpenStack4j.com.  See http://www.openstack4j.com/learn/threads/

Let me know if this helps for issue closure

**Comment by kaaas** [comment]
oh, i did not know that, should have googled a bit more. thanks, works now:)
