### ISSUE TITLE
Attempt to use updateStack aPI results in Fail: Can not deserialize instance of java.lang.String out of START_OBJECT token at [Source: org.apache.http.conn.EofSensorInputStream@4830816d; line: 1, column: 1]

### ISSUE THREAD

**Issue by omryd** [gondor/openstack4j#223]
Attempt to use updateStack aPI results in “Fail: Can not deserialize instance of java.lang.String out of START_OBJECT token at [Source: org.apache.http.conn.EofSensorInputStream@4830816d; line: 1, column: 1]”

I am trying to update an existing stack, which was successfully deployed using ps.heat().stacks().create() method.
Regardless of the update method (template as yaml string or URL of existing template) the update attempt results with an error : 
Fail: Can not deserialize instance of java.lang.String out of START_OBJECT token at [Source: org.apache.http.conn.EofSensorInputStream@4830816d; line: 1, column: 1]

In the first case, when attempting to update the stack using template string, I have provided the method with the same template string which I used when created the stack.
When attempted to update the stack with the same template string manually (via horizon UI) the update succeeded.

In the second case, when attempting to update the stack using a template which I have uploaded to a public server (accessible from the OS node), by providing the method with the URL of the template, I get the same error, 
but again, when attempting to update the stack manually, the operation succeeds.

In the URL case, this is the simple template I am using:

heat_template_version: '2013-05-23'
resources: 
 
  server1:
    type: OS::Nova::Server
    properties:
      networks:
       - uuid: 92ff2ed5-558e-4d21-ae7e-e2959ac8e96d
      availability_zone: zone0
      name: vm1
      flavor: SMALL_1
      image: 4a79ab4a-96f1-4858-8338-c4df4b5c6dca
  server2:
    type: OS::Nova::Server
    properties:
      networks:
       - uuid: 92ff2ed5-558e-4d21-ae7e-e2959ac8e96d
      availability_zone: zone0
      name: vm2
      flavor: SMALL_1
      image: 4a79ab4a-96f1-4858-8338-c4df4b5c6dca
                  
Where all entities listed above have the relevant UUIDs (same network for both servers, same image for both servers, flavor SMALL_1 exists on OS node)

Using this template in OS UI succeeds, when attempting to update an existing stack, but fails when using the openstack4j update method.

Stack trace:
ClientResponseException{message=Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: org.apache.http.conn.EofSensorInputStream@4830816d; line: 1, column: 1], status=0, status-code=CODE_UNKNOWN}
at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:126)
at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:35)
at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:23)
at org.openstack4j.openstack.heat.internal.StackServiceImpl.update(StackServiceImpl.java:71)

The error occurs within the ToActionResponseFunction class, when attempting to read the HttpResponse response as String.
The response code received when attempting to update the stack is HTTP 400 bad request.

Sp it seems like the sent update request is somewhat invalid.

**Comment by pashtika** [comment]
I'm also facing the same issue 
nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token

Could anyone please help what could the solution?
