### ISSUE TITLE
Assign/Remove floating IP to the server throws JsonMappingException

### ISSUE THREAD

**Issue by vinodborole** [gondor/openstack4j#241]
Following is the code with 2.0.1-SNAPSHOT jar

          private static void listfloatingIps(final OSClient os) {
        final List<? extends FloatingIP> ips = os.compute().floatingIps().list();
        for (final FloatingIP ip : ips) {
            System.out.println(ip);

            if (ip.getInstanceId() == null) {
                final String address = ip.getFloatingIpAddress();
                assignFloatingIp(os, address);
            }
        }
    }

    private static void assignFloatingIp(final OSClient os, final String IpId) {
        System.out.println("Assigning floating Ip");
        final Server server = os.compute().servers().get("a382b060-c7a4-4107-ada9-b31be67e7f2a");
        final ActionResponse ar = os.compute().floatingIps().addFloatingIP(server, IpId);
        ActionResponse ar1 = os.compute().floatingIps().removeFloatingIP(server, IpId);
        System.out.println("Assigned");
        System.out.println(ar.isSuccess());
    }

Below is the Exception

                    [org.openstack4j.connectors.httpclient.HttpResponseImpl] ERROR: Can not deserialize       instance of java.lang.String out of START_OBJECT token
               at [Source: org.apache.http.conn.EofSensorInputStream@22ab57; line: 1, column: 1]
              com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of             java.lang.String out of START_OBJECT token
           at [Source: org.apache.http.conn.EofSensorInputStream@22ab57; line: 1, column: 1]
                  at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
     at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749)
    at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:59)
    at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:12)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1269)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:864)
    at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:129)
    at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:37)
    at org.openstack4j.openstack.compute.internal.BaseComputeServices.invokeAction(BaseComputeServices.java:22)
    at org.openstack4j.openstack.compute.internal.ComputeFloatingIPServiceImpl.addFloatingIP(ComputeFloatingIPServiceImpl.java:68)
    at org.openstack4j.openstack.compute.internal.ComputeFloatingIPServiceImpl.addFloatingIP(ComputeFloatingIPServiceImpl.java:76)
    at Test4j.assignFloatingIp(Test4j.java:72)
    at Test4j.listfloatingIps(Test4j.java:64)
    at Test4j.getVolumeId(Test4j.java:49)
    at Test4j.main(Test4j.java:142)
                                 Exception in thread "main" ClientResponseException{message=Can not deserialize instance of java.lang.String out of START_OBJECT token

                       at [Source: org.apache.http.conn.EofSensorInputStream@22ab57; line: 1, column: 1],                    status=0, status-code=CODE_UNKNOWN}
                         at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:132)
                         at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:37)
                          at org.openstack4j.openstack.compute.internal.BaseComputeServices.invokeAction(BaseComputeServices.java:22)
                             at org.openstack4j.openstack.compute.internal.ComputeFloatingIPServiceImpl.addFloatingIP(ComputeFloatingIPServiceImpl.java:68)
                               at        org.openstack4j.openstack.compute.internal.ComputeFloatingIPServiceImpl.addFloatingIP(ComputeFloatingIPServiceImpl.java:76)
                        at Test4j.assignFloatingIp(Test4j.java:72)
                  at Test4j.listfloatingIps(Test4j.java:64)
                 at Test4j.getVolumeId(Test4j.java:49)
                   at Test4j.main(Test4j.java:142)
                  Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of     java.lang.String out of START_OBJECT token
                   at [Source: org.apache.http.conn.EofSensorInputStream@22ab57; line: 1, column: 1]
                   at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
                    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749)
                   at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:59)
                   at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:12)
                    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1269)
                     at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:864)
                       at       org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:129)
                         ... 8 more

**Comment by gondor** [comment]
I just made a fix that should address this issue.  It's in 2.0.2-SNAPSHOT / Master branch if on source.  I just checked in the fix as well as deployed the new 2.0.2-SNAPSHOT to maven.  Let me know.

**Comment by vinodborole** [comment]
Thanks @gondor will test and let you know

**Comment by vinodborole** [comment]
I do not see the exception now for assigning floating IP. however, the removeFloatingIP code returns true but it does nothing on the openstack side.

**Comment by gondor** [comment]
I'd enable HTTP Logging  - OSFactory.enableHttpLoggingFilter(true); - 
and look at the raw response.  May be an OpenStack issue.  They do have bugs in various releases and we do catch them :)  If the response clearly is a failure (400+ error) then I'd love to see the response to address this.

**Comment by vinodborole** [comment]
Will check and get back to you @gondor

**Comment by vinodborole** [comment]
We enabled logging but it does not seem to be working with httpclient jars, later we tried doing the same implementation with Jclouds library to ensure if its the openstack issue, but it turns out that through jclouds api it works, hence its not an openstack issue. the version we are using is havana

**Comment by gondor** [comment]
Did you enable the logging before you made the call?  This has to happen before authentication typically.  Should of been outputted to System.err.


Could you try the Jersey2 connector to verify?  HttpClient is a new beta connector which is why we see issues popping up still.  Logging definitely works with Jersey2.
