### ISSUE TITLE
Unable to pass SampleCriteria as a parameter in sample() method 

### ISSUE THREAD

**Issue by nstanogias** [gondor/openstack4j#261]
Hi gondor,

Im a student working on my thesis and Im using Openstack4j to get some metrics from the instances that are running.
When I pass SampleCriteria into sample() method I get the following output:

Exception in thread "main" ClientResponseException{message=Status: 400, Reason: Bad Request, status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:53)
	at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:66)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:164)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:158)
	at org.openstack4j.openstack.telemetry.internal.MeterServiceImpl.samples(MeterServiceImpl.java:64)
	at com.mycompany.mavenproject1.Openstack4jExample.run(Openstack4jExample.java:81)
	at com.mycompany.mavenproject1.Openstack4jExample.main(Openstack4jExample.java:97)

I ve tried using the examples below:

        SampleCriteria sc = new SampleCriteria();
        List<? extends Sample> samples = os.telemetry().meters().samples("cpu_util", sc.timestamp(SampleCriteria.Oper.EQUALS, new Date()));

List<? extends Sample> samples = os.telemetry().meters().samples("cpu_util", sc.resource("51cc6ede-4a8c-4c4b-9f4a-9bcc19e90ba8"));

If I take out the SampleCriteria parameter everything is working fine. 
Am I doing something wrong?

**Comment by gondor** [comment]
Deploying 2.0.2 Release Tonight - Closing - Re-Open or Comment if issue was not resolved
