### ISSUE TITLE
SwiftAccount account = os.objectStorage().account().get();

### ISSUE THREAD

**Issue by OnePieceHX** [gondor/openstack4j#327]
wnExceptionMapper] - Unknown Exception: class java.lang.NullPointerException
java.lang.NullPointerException
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.header(HttpResponseImpl.java:94) ~[openstack4j-resteasy-2.0.2-SNAPSHOT.jar:?]
	at org.openstack4j.openstack.storage.object.functions.ParseAccountFunction.apply(ParseAccountFunction.java:26) ~[openstack4j-core-2.0.2-SNA
PSHOT.jar:?]
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageAccountServiceImpl.get(ObjectStorageAccountServiceImpl.java:27) ~[opensta
ck4j-core-2.0.2-SNAPSHOT.jar:?]

**Comment by gondor** [comment]
Thanks for finding this bug and reporting it.  Just checked in the fix and deployed a new `2.0.4-SNAPSHOT`.   Let me know if this works for you!

**Comment by symcssn** [comment]
you also get a NPE for ObjectService.list(containerDoesNotExist). I've tried it with the latest update of 2.0.4-SNAPSHOT
