### ISSUE TITLE
Exception when deleting an unexisting Glance image

### ISSUE THREAD

**Issue by bsemp** [gondor/openstack4j#336]
Starting from version 2.0.2, when trying to delete an already deleted Glance image or an image with a bad ID, Openstack API responds with a _404 not found_ error but Openstack4J throws an `JsonMappingException` instead of setting `ActionResponse.isSuccess()` to `false`.

Other delete functions behaves as expected.

```java
String bad_image_id = "1111";
ActionResponse response = client.images().delete(bad_image_id);
```

```

2015/04/21 18:41:39:216 CEST [DEBUG] MainClientExec - Executing request DELETE /v1/images/1111 HTTP/1.1
2015/04/21 18:41:39:216 CEST [DEBUG] MainClientExec - Target auth state: UNCHALLENGED
2015/04/21 18:41:39:216 CEST [DEBUG] MainClientExec - Proxy auth state: UNCHALLENGED
2015/04/21 18:41:39:216 CEST [DEBUG] headers - http-outgoing-1 >> DELETE /v1/images/1111 HTTP/1.1
2015/04/21 18:41:39:216 CEST [DEBUG] headers - http-outgoing-1 >> Accept: application/json; charset=utf-8
2015/04/21 18:41:39:216 CEST [DEBUG] headers - http-outgoing-1 >> User-Agent: OpenStack4j / OpenStack Client
2015/04/21 18:41:39:216 CEST [DEBUG] headers - http-outgoing-1 >> X-Auth-Token: [...]
2015/04/21 18:41:39:220 CEST [DEBUG] headers - http-outgoing-1 >> Host: test.example.com:9292
2015/04/21 18:41:39:220 CEST [DEBUG] headers - http-outgoing-1 >> Connection: Keep-Alive
2015/04/21 18:41:39:220 CEST [DEBUG] headers - http-outgoing-1 >> Accept-Encoding: gzip,deflate
2015/04/21 18:41:39:220 CEST [DEBUG] wire - http-outgoing-1 >> "DELETE /v1/images/1111 HTTP/1.1[\r][\n]"
2015/04/21 18:41:39:220 CEST [DEBUG] wire - http-outgoing-1 >> "Accept: application/json; charset=utf-8[\r][\n]"
2015/04/21 18:41:39:220 CEST [DEBUG] wire - http-outgoing-1 >> "User-Agent: OpenStack4j / OpenStack Client[\r][\n]"
2015/04/21 18:41:39:221 CEST [DEBUG] wire - http-outgoing-1 >> "X-Auth-Token: [...]"
2015/04/21 18:41:39:229 CEST [DEBUG] wire - http-outgoing-1 >> "Host: test.example.com:9292[\r][\n]"
2015/04/21 18:41:39:229 CEST [DEBUG] wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
2015/04/21 18:41:39:229 CEST [DEBUG] wire - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2015/04/21 18:41:39:230 CEST [DEBUG] wire - http-outgoing-1 >> "[\r][\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "HTTP/1.1 404 Not Found[\r][\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "Content-Length: 88[\r][\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "Content-Type: text/plain; charset=UTF-8[\r][\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "X-Openstack-Request-Id: req-204bc689-8dc0-4d21-a7bd-2fcbd8e4482e[\r][\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "Date: Tue, 21 Apr 2015 16:41:39 GMT[\r][\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "[\r][\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "404 Not Found[\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "[\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "The resource could not be found.[\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << "[\n]"
2015/04/21 18:41:39:396 CEST [DEBUG] wire - http-outgoing-1 << " Image with identifier 1111 not found  "
2015/04/21 18:41:39:397 CEST [DEBUG] headers - http-outgoing-1 << HTTP/1.1 404 Not Found
2015/04/21 18:41:39:397 CEST [DEBUG] headers - http-outgoing-1 << Content-Length: 88
2015/04/21 18:41:39:397 CEST [DEBUG] headers - http-outgoing-1 << Content-Type: text/plain; charset=UTF-8
2015/04/21 18:41:39:397 CEST [DEBUG] headers - http-outgoing-1 << X-Openstack-Request-Id: req-204bc689-8dc0-4d21-a7bd-2fcbd8e4482e
2015/04/21 18:41:39:397 CEST [DEBUG] headers - http-outgoing-1 << Date: Tue, 21 Apr 2015 16:41:39 GMT
2015/04/21 18:41:39:397 CEST [DEBUG] MainClientExec - Connection can be kept alive indefinitely
2015/04/21 18:41:39:406 CEST [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 1][route: {}->http://test.example.com:9292] can be kept alive indefinitely
2015/04/21 18:41:39:406 CEST [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {}->http://test.example.com:9292][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
[org.openstack4j.connectors.httpclient.HttpResponseImpl] ERROR: Can not deserialize instance of java.util.LinkedHashMap out of VALUE_NUMBER_INT token
 at [Source: org.apache.http.conn.EofSensorInputStream@402badd6; line: 1, column: 1]
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of VALUE_NUMBER_INT token
 at [Source: org.apache.http.conn.EofSensorInputStream@402badd6; line: 1, column: 1]
*****CloudUtils static init: welcome. Started on 2015/04/21 18:41:39.412 +0200, version is R2015x.D58HF1
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:745)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:307)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1269)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:864)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:130)
	at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:26)
	at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:21)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:30)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:68)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)
	at org.openstack4j.openstack.image.internal.ImageServiceImpl.delete(ImageServiceImpl.java:106)
	at com.example.openstack.Openstack4JWrapper$46.execute(Openstack4JWrapper.java:722)
	at com.example.openstack.RetryExecutorHelper.doWithRetry(RetryExecutorHelper.java:15)
	at com.example.openstack.RetryExecutorHelper.doWithRetry(RetryExecutorHelper.java:35)
	at com.example.openstack.Openstack4JWrapper.deleteImage(Openstack4JWrapper.java:718)
	at com.example.Openstack4JTest.main(Openstack4JTest.java:84)
Exception in thread "main" ClientResponseException{message=Can not deserialize instance of java.util.LinkedHashMap out of VALUE_NUMBER_INT token
 at [Source: org.apache.http.conn.EofSensorInputStream@402badd6; line: 1, column: 1], status=0, status-code=CODE_UNKNOWN}
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:133)
	at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:26)
	at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:21)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:30)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:68)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)
	at org.openstack4j.openstack.image.internal.ImageServiceImpl.delete(ImageServiceImpl.java:106)
	at com.example.openstack.Openstack4JWrapper$46.execute(Openstack4JWrapper.java:722)
	at com.example.openstack.RetryExecutorHelper.doWithRetry(RetryExecutorHelper.java:15)
	at com.example.openstack.RetryExecutorHelper.doWithRetry(RetryExecutorHelper.java:35)
	at com.example.openstack.Openstack4JWrapper.deleteImage(Openstack4JWrapper.java:718)
	at com.example.Openstack4JTest.main(Openstack4JTest.java:84)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of VALUE_NUMBER_INT token
 at [Source: org.apache.http.conn.EofSensorInputStream@402badd6; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:745)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:307)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1269)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:864)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:130)
	... 12 more
Java Result: 1
BUILD SUCCESSFUL (total time: 1 second)
```

**Comment by bsemp** [comment]
Here my analysis of the issue : 

I'm working with Openstack Juno version.

The error occurs when deserializing error response body from openstack server in function `ResponseToActionResponse.apply`

This function assume the body will be a json string that can be deserialized as a Map : 
`Map<String, Object> map = response.readEntity(Map.class);`

Compute and Storage services, as expected,  respond with a json object describing the error:

    avr. 24, 2015 2:52:10 PM org.glassfish.jersey.filter.LoggingFilter log
    INFO: 2 * Client response received on thread main
    2 < 404
    2 < Content-Length: 78
    2 < Content-Type: application/json; charset=UTF-8
    2 < Date: Fri, 24 Apr 2015 12:52:10 GMT
    2 < X-Compute-Request-Id: req-c8784aee-d844-459e-9a98-99dcd56b7be9
    2 < X-Openstack-Request-Id: req-c8784aee-d844-459e-9a98-99dcd56b7be9
    {"itemNotFound": {"message": "The resource could not be found.", "code": 404}}

but Image service, oddly responds with plain text that fails to be deserialized as Map :

    avr. 24, 2015 2:49:51 PM org.glassfish.jersey.filter.LoggingFilter log
    INFO: 2 * Client response received on thread main
    2 < 404
    2 < Content-Length: 88
    2 < Content-Type: text/plain; charset=UTF-8
    2 < Date: Fri, 24 Apr 2015 12:49:51 GMT
    2 < X-Openstack-Request-Id: req-23ec663c-f569-4c8c-b73c-3f1fc27bc7b2
    404 Not Found
    
    The resource could not be found.
    
     Image with identifier 1111 not found

**Comment by gondor** [comment]
Thanks for the extra info.  My installs were the exact same behavior.  Responding with text/plain even though we stated Accept: application/json.  Seems like a glitch on the glance API side.  Regardless it's a good edgecase to handle so I added a fix for these scenarios.    Checked in and `2.0.4-SNAPSHOT` deployed

**Comment by bsemp** [comment]
It works.
Thanks a lot.
