### ISSUE TITLE
Deserialization error with HttpURL connector

### ISSUE THREAD

**Issue by bsemp** [gondor/openstack4j#376]
When using HttpURL connector, deleting a non existing floating ip throws an NullPointerException.

    INFO: MockWebServer[8774] received request: DELETE /v2/b80f8d4e28b74188858b654cb1fccf7d/os-floating-ips/192.168.0.10 HTTP/1.1 and responded: HTTP/1.1 202 OK
    [org.openstack4j.connectors.http.HttpResponseImpl] ERROR: null
    java.lang.NullPointerException
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:790)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912)
        at org.openstack4j.connectors.http.HttpResponseImpl.readEntity(HttpResponseImpl.java:141)
        at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:31)
        at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:22)
        at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:45)
        at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:27)
        at org.openstack4j.openstack.compute.internal.ComputeFloatingIPServiceImpl.deallocateIP(ComputeFloatingIPServiceImpl.java:58)
        at org.openstack4j.api.compute.FloatingIPTests.deallocateFloatingIP(FloatingIPTests.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:767)
        at org.testng.TestRunner.run(TestRunner.java:617)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
        at org.testng.SuiteRunner.run(SuiteRunner.java:240)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
        at org.testng.TestNG.run(TestNG.java:1031)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
        
        
    deallocateFloatingIP(org.openstack4j.api.compute.FloatingIPTests)  Time elapsed: 0.003 sec  <<< FAILURE!
    org.openstack4j.api.exceptions.ClientResponseException: null
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:790)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912)
        at org.openstack4j.connectors.http.HttpResponseImpl.readEntity(HttpResponseImpl.java:141)
        at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:31)
        at org.openstack4j.core.transport.functions.ResponseToActionResponse.apply(ResponseToActionResponse.java:22)
        at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:45)
        at org.openstack4j.openstack.compute.functions.ToActionResponseFunction.apply(ToActionResponseFunction.java:27)
        at org.openstack4j.openstack.compute.internal.ComputeFloatingIPServiceImpl.deallocateIP(ComputeFloatingIPServiceImpl.java:58)
        at org.openstack4j.api.compute.FloatingIPTests.deallocateFloatingIP(FloatingIPTests.java:105)

**Comment by gondor** [comment]
Fixed added a a new snapshot deployed
