### ISSUE TITLE
What is HttpStatus code 0?

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#380]
I get many exceptions with status code 0 for various reasons. What is meant to be used for?

**Comment by symcssn** [comment]
According to the code, it states 'An exception which is thrown when a connection/IO exception has occurred with the remote host'. Under what circumstances do we get an connection/IO exception?

**Comment by vishvesh** [comment]
Under what context is your request invoked? What is nature of your request?

**Comment by gondor** [comment]
The I/O is thrown from Java indicating either:

a.) The connection timed out
b.) The remote host responded but closed the connection
c.) Remote port isn't available
etc..

These kinds of errors would not be related to OpenStack4j.  Are you using a VPN or could the remote openstack be over-taxed?

**Comment by symcssn** [comment]
HI @gondor 

I believe we are running into b.

**Comment by symcssn** [comment]
HI @gondor 

I believe we are getting most of our ClientTimeoutException from possibly b. We are getting this ClientException very frequently. Would you please enable checking for stale connection in the HttpClientFactory please?

 https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.html

http://www.baeldung.com/httpclient-connection-management

Thanks @gondor ,

symcssn

**Comment by symcssn** [comment]
@vishvesh 

We get this for random reasons: listing, getting, downloading, etc...





```
org.openstack4j.api.exceptions.ConnectionException: Connect to ****  failed: Connection timed out
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:55) ~[openstack4j-httpclient-2.0.2.jar:na]
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:29) ~[openstack4j-httpclient-2.0.2.jar:na]
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.executeWithResponse(BaseOpenStackService.java:173) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.download(ObjectStorageObjectServiceImpl.java:190) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.download(ObjectStorageObjectServiceImpl.java:182) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.openstack.storage.object.domain.SwiftObjectImpl.download(SwiftObjectImpl.java:102) ~[openstack4j-2.0.2.jar:na]

Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to ******  failed: Connection timed out
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106) ~[httpclient-4.3.6.jar:4.3.6]
	at org.openstack4j.connectors.httpclient.HttpCommand.execute(HttpCommand.java:149) ~[openstack4j-httpclient-2.0.2.jar:na]
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:60) ~[openstack4j-httpclient-2.0.2.jar:na]
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:53) ~[openstack4j-httpclient-2.0.2.jar:na]
	... 24 common frames omitted
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_20]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_20]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_20]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_20]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_20]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_20]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:244) ~[httpclient-4.3.6.jar:4.3.6]
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125) ~[httpclient-4.3.6.jar:4.3.6]
	... 36 common frames omitted

```

**Comment by gondor** [comment]
Since HttpClient offers so many configuration tweaks I thought it was best to open it up and allow interception prior to the client being created.  This will allow you to hook in and change anything you want.

See Issue #392 which has been checked in and deployed.

**Comment by symcssn** [comment]
Thanks @gondor . 

I look forward to  trying the interceptor out.

**Comment by symcssn** [comment]
Do you know when you are planning to release 2.0.4 as an official release?
(I will play with the interceptor soon :) )

**Comment by gondor** [comment]
Hopefully in the next week.  Try to play with the interceptor before I cut a release so you know it works ahead of time, etc.

**Comment by symcssn** [comment]
The interceptor looks good. I've made a few comments on the page:
https://github.com/gondor/openstack4j/issues/392
