### ISSUE TITLE
error occurred during  listEndpoints in openstack4j 2.0.2

### ISSUE THREAD

**Issue by mathews** [gondor/openstack4j#405]
javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:866)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:783)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)[166:org.glassfish.jersey.core.jersey-client:2.12.0]
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:111)[166:org.glassfish.jersey.core.jersey-client:2.12.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:399)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:108)[166:org.glassfish.jersey.core.jersey-client:2.12.0]
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.readEntity(HttpResponseImpl.java:112)[171:openstack4j-jersey2-jdk16:2.0.2]
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:56)[170:openstack4j-core:2.0.2]
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:19)[170:openstack4j-core:2.0.2]
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:62)[171:openstack4j-jersey2-jdk16:2.0.2]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)[170:openstack4j-core:2.0.2]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)[170:openstack4j-core:2.0.2]
	at org.openstack4j.openstack.identity.internal.ServiceManagerServiceImpl.listEndpoints(ServiceManagerServiceImpl.java:68)[170:openstack4j-core:2.0.2]
	at 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.net.URI from String value 'http://10.0.2.5:8776/v1/%(tenant_id)s': not a valid textual representationproblem: Malformed escape pair at index 24: http://10.0.2.5:8776/v1/%(tenant_id)s
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@5f56da3; line: 1, column: 509] (through reference chain: org.openstack4j.openstack.identity.domain.ServiceEndpoints["endpoints"]->org.openstack4j.openstack.identity.domain.KeystoneServiceEndpoint["internalurl"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:797)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:133)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:232)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:106)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:800)[153:com.fasterxml.jackson.jaxrs.jackson-jaxrs-base:2.4.0]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:264)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:234)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:154)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851)[167:org.glassfish.jersey.core.jersey-common:2.12.0]
	... 22 more
Caused by: java.lang.IllegalArgumentException: Malformed escape pair at index 24: http://10.0.2.5:8776/v1/%(tenant_id)s
	at java.net.URI.create(URI.java:859)[:1.7.0_79]
	at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std._deserialize(FromStringDeserializer.java:210)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:122)[158:com.fasterxml.jackson.core.jackson-databind:2.4.1.3]
	... 41 more
Caused by: java.net.URISyntaxException: Malformed escape pair at index 24: http://10.0.2.5:8776/v1/%(tenant_id)s
	at java.net.URI$Parser.fail(URI.java:2829)[:1.7.0_79]
	at java.net.URI$Parser.scanEscape(URI.java:2959)[:1.7.0_79]
	at java.net.URI$Parser.scan(URI.java:2982)[:1.7.0_79]
	at java.net.URI$Parser.checkChars(URI.java:3000)[:1.7.0_79]
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)[:1.7.0_79]
	at java.net.URI$Parser.parse(URI.java:3034)[:1.7.0_79]
	at java.net.URI.<init>(URI.java:595)[:1.7.0_79]
	at java.net.URI.create(URI.java:857)[:1.7.0_79]
	... 43 more

**Comment by vinodborole** [comment]
@mathews  is this still an issue, if not please close this

**Comment by keanesf** [comment]
I am experiencing this issue as well.

org.jboss.resteasy.spi.ReaderException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.net.URI from String "http://10.1.1.2:8776/v2/%(tenant_id)s": not a valid textual representation, problem: Malformed escape pair at index 24: http://10.1.1.2:8776/v2/%(tenant_id)s
 at [Source: org.jboss.resteasy.client.core.SelfExpandingBufferredInputStream@133a0f36; line: 1, column: 29] (through reference chain: org.openstack4j.openstack.identity.v2.domain.KeystoneServiceEndpoint$ServiceEndpoints["endpoints"]->java.util.ArrayList[0]->org.openstack4j.openstack.identity.v2.domain.KeystoneServiceEndpoint["adminurl"])
        at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:469)
        at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:377)
        at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:350)
        at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:344)
        at org.openstack4j.connectors.resteasy.HttpResponseImpl.readEntity(HttpResponseImpl.java:116)
        at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:66)
        at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:64)
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:220)
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
        at org.openstack4j.openstack.identity.v2.internal.ServiceManagerServiceImpl.listEndpoints(ServiceManagerServiceImpl.java:68)
        at com.att.cso.astra.inventory.common.collector.client.OpenStackClient.getRegionNames(OpenStackClient.java:79)
        at com.att.cso.astra.inventory.subnet.service.SubnetCollectorServer.collectOpenStackSubnets(SubnetCollectorServer.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.net.URI from String "http://10.1.1.2:8776/v2/%(tenant_id)s": not a valid textual representation, problem: Malformed escape pair at index 24: http://10.1.1.2:8776/v2/%(tenant_id)s
 at [Source: org.jboss.resteasy.client.core.SelfExpandingBufferredInputStream@133a0f36; line: 1, column: 29] (through reference chain: org.openstack4j.openstack.identity.v2.domain.KeystoneServiceEndpoint$ServiceEndpoints["endpoints"]->java.util.ArrayList[0]->org.openstack4j.openstack.identity.v2.domain.KeystoneServiceEndpoint["adminurl"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1410)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:133)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
        at org.jboss.resteasy.core.interception.MessageBodyReaderContextImpl.proceed(MessageBodyReaderContextImpl.java:105)
        at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:433)
        ... 25 more
Caused by: java.lang.IllegalArgumentException: Malformed escape pair at index 24: http://10.1.1.2:8776/v2/%(tenant_id)s
        at java.net.URI.create(URI.java:852)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std._deserialize(FromStringDeserializer.java:223)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:116)
        ... 41 more
Caused by: java.net.URISyntaxException: Malformed escape pair at index 24: http://10.1.1.2:8776/v2/%(tenant_id)s
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.scanEscape(URI.java:2978)
        at java.net.URI$Parser.scan(URI.java:3001)
        at java.net.URI$Parser.checkChars(URI.java:3019)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 43 more

**Comment by auhlig** [comment]
Please use the latest version, which is currently 3.0.4.

**Comment by keanesf** [comment]
I was using 3.0.3 version. Error still occurs with 3.0.4 version.

**Comment by auhlig** [comment]
Could you try a different connector?

**Comment by keanesf** [comment]
I tired the openstack4j-resteasy, openstack4j-okhttp and openstack4j-httpclient connectors. I still got the same error.

**Comment by vinodborole** [comment]
I am not sure if this is related check this link - https://ask.openstack.org/en/question/778/is-it-normal-to-see-tenant_ids-when-listing-keystone_endpoints/

In your case the URL is ttp://10.1.1.2:8776/v2/%(tenant_id)s  here you have % instead of $

References:
http://stackoverflow.com/questions/12422256/urisyntaxexception-how-to-deal-with-urls-with
#924
