### ISSUE TITLE
httpclient connector leaks connections on failed authentication attempts and eventually hangs

### ISSUE THREAD

**Issue by petergardfjall** [gondor/openstack4j#412]
The openstack4j httpclient connector appears to be leaking connections on failed authentication attempts. This eventually causes the application using the `OSFactory` to hang (waiting for a client connection from the httpclient connection pool). This issue may very well be related to issue #400 and/or #411.

The following simple snippet of code is sufficient, at least for me, to provoke a hanging application.

```
	public static void main(String[] args) {
		String keystoneUrl = "https://identity1.citycloud.com:5000/v3/";
		String userId = "wrong";
		String password = "wrong";
		String projectId = "wrong";

		int RETRIES = 3;
		for (int i = 1; i <= RETRIES; i++) {
			System.out.println(String
					.format("authentication attempt %d ...", i));
			try {
				OSClient client = OSFactory
						.builderV3()
						.endpoint(keystoneUrl)
						.credentials(userId, password)
						.scopeToProject(Identifier.byId(projectId),
								Identifier.byId(projectId)).authenticate();
				System.out.println("authentication success!");
			} catch (AuthenticationException e) {
				System.out.println(String.format("authentication failure: %s",
						e.getMessage()));
			} catch (Exception e) {
				System.out.println(String.format("other error: %s",
						e.getMessage()));
			}
		}
	}
```

The code needs the dependencies `org.pacesys:openstack4j-core:2.0.4-SNAPSHOT` and `org.pacesys:openstack4j-httpclient:2.0.4-SNAPSHOT` to run.

After three failed attempts to authenticate, the next call to `OSFactory.builderV3()...authenticate()` will hang.

A thread dump reveals that the main thread is waiting for a connection from the httpclient's connection pool:

```
"main" prio=10 tid=0x00007fe6c400b800 nid=0x606a waiting on condition [0x00007fe6cd6fa000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007afb70310> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:133)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:282)
	at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:64)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:177)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:170)
	at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:102)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:244)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:231)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:173)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.openstack4j.connectors.httpclient.HttpCommand.execute(HttpCommand.java:122)
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:60)
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:53)
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:29)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:126)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:48)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:141)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:105)
	at bug.openstack4j.AuthConnectionLeakageIssue.main(AuthConnectionLeakageIssue.java:34)

   Locked ownable synchronizers:
	- None
```

**Comment by petergardfjall** [comment]
Note also that the same code works well with, for example, the jersey2 connector (`org.pacesys:openstack4j-jersey2:2.0.4-SNAPSHOT`).

**Comment by symcssn** [comment]
I ran into this problem today actually. 

@gondor  the problem is stemming from the ```OSAuthenticator```. We are throwing an exception before getting the opportunity to close the response: ```throw mapException(response.getStatusMessage(), response.getStatus());```

**Comment by gondor** [comment]
Thanks for all the info. Issue fixed and new SNAPSHOT deployed

**Comment by petergardfjall** [comment]
Great Jeremy!

**Comment by petergardfjall** [comment]
I tried out the code with most recent release and this time it passed without hanging, so consider the fix verified!
