### ISSUE TITLE
Help！！！！！！create server error through blockDeviceMappingBuilder

### ISSUE THREAD

**Issue by houyu533** [gondor/openstack4j#424]
note:
     I want create server through blockDeviceMappingBuilder（sourceType is image and destinationType is volume）, I can't find set volume size from api.

code:

BlockDeviceMappingBuilder blockDeviceMappingBuilder = Builders.blockDeviceMapping().uuid("2eceacf0-8e4d-4de1-a92e-b508b6a0b6fa").deviceName("/dev/vda").bootIndex(0).sourceType("image").destinationType("volume").deleteOnTermination(true);
		 
ServerCreate sc = Builders.server().name("aaagl").flavor("027b31f3-13e1-404d-ba12-179ada180971").networks(netNetworkIds).blockDevice(blockDeviceMappingBuilder.build()).availabilityZone("tcloud-380").build();
// Boot the Server
final Server server = adminOs.compute().servers().boot(sc);

error:

	Exception in thread "main" ClientResponseException{message=Images with destination_type 'volume' need to have a non-zero size specified, status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:98)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:40)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:19)
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:62)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.boot(ServerServiceImpl.java:122)
	at com.tcl.aot.third.s3.OpenstackTest.main(OpenstackTest.java:130

**Comment by gondor** [comment]
What version of OpenStack4j are you using and what version of OpenStack are you testing this against?

**Comment by gondor** [comment]
Ok, found the issue.. volume size is needed when the source_type is Image and destination type is Volume in your case.  Added new "volumeSize(int v)" to the existing builder to specify the desired size of the destination volume as per OpenStack Nova's API

New 2.0.5-SNAPSHOT deployed with fix and code checked in

**Comment by houyu533** [comment]
thank you for your answer，2.0.5-SNAPSHOT is ok.

**Comment by victorcai0922** [comment]
when boot instance from volume, there is an error "Block device xxxx is not bootable". but in openstack dashboard the volume is bootable.

**Comment by victorcai0922** [comment]
which api can query the volume is bootable
