### ISSUE TITLE
NullPointerException in case of v3 authentication

### ISSUE THREAD

**Issue by FaoCurse** [gondor/openstack4j#447]
Can not get tenants list by using v3 authentication (v2.0.5):
```
OSClient openStack = OSFactory.builderV3()
                    .endpoint("url")
                    .credentials("login", "password", "default")
                    .authenticate();
OSClient osClient = OSFactory.clientFromAccess(openStack.getAccess());
osClient.identity().tenants().list();
```
This code throws NullPointerException when DefaultEndpointURLResolver is trying to get catalogs from token:
```
java.lang.NullPointerException
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.resolveV3(DefaultEndpointURLResolver.java:110)
	at org.openstack4j.openstack.identity.internal.DefaultEndpointURLResolver.findURL(DefaultEndpointURLResolver.java:50)
	at org.openstack4j.openstack.internal.OSClientSession.getEndpoint(OSClientSession.java:202)
	at org.openstack4j.core.transport.HttpRequest$RequestBuilder.build(HttpRequest.java:405)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:177)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:172)
	at org.openstack4j.openstack.identity.internal.TenantServiceImpl.list(TenantServiceImpl.java:23)
```

**Comment by FaoCurse** [comment]
Probled solved, missing follow string:
.scopeToDomain(Identifier.byName(endpoint.getDomain()))
