### ISSUE TITLE
 java.lang.NullPointerException when getting servers list

### ISSUE THREAD

**Issue by santuari** [gondor/openstack4j#458]
When I run this command admin.compute().servers().list(), sometime I get this error:

Exception in thread "Thread-14" java.lang.NullPointerException
	at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:84)
	at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:79)
	at org.openstack4j.openstack.internal.BaseOpenStackService.get(BaseOpenStackService.java:46)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:87)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:75)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.list(ServerServiceImpl.java:67)

**Comment by symcssn** [comment]
@santuari 

Is your application mutli-threaded?

**Comment by santuari** [comment]
Yes

**Comment by symcssn** [comment]
Would you please check how you are authenticating across threads?

**Comment by gondor** [comment]
Please review this content if your using it between threads for some guidance.
http://openstack4j.com/learn/threads/

**Comment by symcssn** [comment]
@gondor 

I'm thinking about throwing some exception if the session object is null with a message like "The session object has not been set."  The NPE is really misleading. What do you think?

**Comment by gondor** [comment]
@symcssn Send me a PR for me to review and we can go from there.   I like the idea, just want to see what the messaging looks like.

**Comment by symcssn** [comment]
https://github.com/gondor/openstack4j/pull/476
