### ISSUE TITLE
ClientResponseException

### ISSUE THREAD

**Issue by LianaN** [gondor/openstack4j#462]
I followed this tutorial to get started with OpenStack4j in Java:
http://www.openstack4j.com/learn/getting-started/

```
package test;

import org.openstack4j.api.OSClient;
import org.openstack4j.openstack.OSFactory;

public class Test {
	public static void main(String[] args)
	{
		OSClient os = OSFactory.builder()
                .endpoint("http://...")
                .credentials("test","pwd")
                .tenantName("test")
                .authenticate();
	}
}
```

This is what I get:
```
Exception in thread "main" ClientResponseException{message=Bad Request, status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:100)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:48)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:107)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:71)
	at test.TestSWIFT3.main(Test.java:16)
```

**Comment by elenamarkoska** [comment]
Are your endpoint, credentials and tenant name correct?

**Comment by LianaN** [comment]
Yes, endpoint, credentials and tenant name are 100% correct. Things don't work when I create OSClient from Java.

**Comment by gondor** [comment]
I appears your endpoint is wrong for authenticating.  Could you paste the URI here (feel free to *** out the actual IP or host).  I'm more curious on the port and path of the endpoint.

**Comment by LianaN** [comment]
The endpoint is the following: os.endpoint("http://xxx.xxx.x.xxx:8080/auth/v1.0/");
It's a local machine.

**Comment by gondor** [comment]
I've never seen a v1.0 endpoint for Keystone (Identity) authentication.  What version of OpenStack are your running?

Also by default all installations for authentication are on port 5000 not 8080.  Typical endpoint looks like

http://xxx.xxx.xx.xxx:5000/v2.0

**Comment by gondor** [comment]
Closing until further info received.  Please re-open when there is info to add.

**Comment by rmagarwal1987** [comment]
Local endpoint looks like this http://xxx.xxx.x.xxx:8080/auth/v1.0/
Is there any solution for the above issue?

**Comment by RayOsLei** [comment]
hi ,LianaN
Your problem with me, you solve it?
