### ISSUE TITLE
Connection timeout with openstack4j compute query

### ISSUE THREAD

**Issue by elenamarkoska** [gondor/openstack4j#463]
I'm trying out openstack4j, and I've run into a problem I don't know what could be causing.

Authentication to the cloud went smoothly:

OSClient os = OSFactory.builder()
	                .endpoint("http://xxx.xxx.xxx.xxx:yyyyy/v2.0")
	                .credentials(username,password)
	                .tenantName("admin")
	                .perspective(Facing.PUBLIC)
	                .authenticate();

However, once os is instanciated, I try running the following line:

List<? extends Flavor> flavors = os.compute().flavors().list();

And I get an ConnectionException{message=java.net.ConnectException: Connection timed out: connect, status=0}

What could be causing this?

Thanks in advance.
_______________________________________________________________________________
Stack trace:

Exception in thread "main" ConnectionException{message=java.net.ConnectException: Connection timed out: connect, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:178)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:172)
	at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:32)
	at com.mycompany.app.my_app.OpenStackCom.authOpenStack(OpenStackCom.java:127)
	at com.mycompany.app.my_app.App.main(App.java:18)
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out: connect
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:229)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:656)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:653)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:653)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:388)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:86)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 7 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:321)
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:227)

**Comment by elenamarkoska** [comment]
For anyone interested, I did not find out why it behaves this way, however I did find out that using a connector such as resteasy instead of jersey fixed my problem.
