### ISSUE TITLE
Creating Pseudo Directories

### ISSUE THREAD

**Issue by Mohamedji** [gondor/openstack4j#490]
os.objectStorage().containers().createPath("myfolder1", "/MyFirstContainer/");

where i wanted to create a folder by name myfolder1 in container MyFirstContainer.
running above cmd throws below exception, other all request are working perfectly fine.

Exception in thread "main" ConnectionException{status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.executeWithResponse(BaseOpenStackService.java:189)
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.put(ObjectStorageObjectServiceImpl.java:126)
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageContainerServiceImpl.createPath(ObjectStorageContainerServiceImpl.java:81)
	at com.cloudenabled.filestore.login.main(login.java:41)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:822)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:182)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 6 more
Caused by: org.apache.http.ProtocolException: Content-Length header already present
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:67)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:108)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:174)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:462)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	... 14 more

**Comment by gondor** [comment]
Actually the proper usage (may not fix your issue) is:
```java
os.objectStorage().containers().createPath(containerName, "/my/nested/path");
```

If your still seeing the issue then it's most likely a bug in the REST Easy connector.  Let me know if you still see an exception.

**Comment by gondor** [comment]
@Mohamedji I found the issue in REST Easy w/ the Apache Client.  Issue should be fixed now.  Deployed a new 2.0.7-SNAPSHOT.  Let me know if this addresses it for you.

**Comment by Mohamedji** [comment]
os.objectStorage().containers().createPath(containerName, "/my/nested/path");

returning null


unable to use  2.0.7-SNAPSHOT hence using  2.0.8-SNAPSHOT can you let me know which artifect to use? openstack4j-jersey2, openstack4j-jersey2-jdk16, openstack4j-resteasy, openstack4j-okhttp and openstack4j-httpclient

**Comment by gondor** [comment]
Sorry I meant 2.0.8-SNAPSHOT.  Are you still seeing the exception using 2.0.8-SNAPSHOT?  I tested the fix against Rackspace last night and it created the path fine using the rest easy fix.  As far as connectors jersey2 the default is the most stable and reliable.  Second would be httpclient with resteasy being the least used/tested

**Comment by Mohamedji** [comment]
Getting below warning: with 2.0.8-SNAPSHOT jersey2 & 
os.objectStorage().containers().createPath(containerName, "/my/nested/path"); returns null

Nov 04, 2015 12:59:35 AM org.glassfish.jersey.client.JerseyInvocation validateHttpMethodAndEntity
WARNING: Entity must not be null for http method PUT.

Also i am able to create a pseudo folder via openstack horizon & curl

**Comment by gondor** [comment]
Ok do me a quick favor.  Go back to 2.0.7 SNAPSHOT and try with Jersey2.  If that works I'm going to revert the change I made to Resteasy in 2.0.8 since it was an issue with it and I was simply trying to workaround it but it's clearing affecting other connectors.

**Comment by Mohamedji** [comment]
same returning null....

**Comment by gondor** [comment]
So odd.. even with Resteasy I'm getting back the ETag on that call (this is against Rackspace).  I'll have to try this on my Juno install when I get home later.

**Comment by Mohamedji** [comment]
Many thanks for your support sir.

Currently i am using below release with below dependencies everything is working fine except pseudo folder creation.

 <dependency>
  <groupId>org.pacesys</groupId>
  <artifactId>openstack4j-core</artifactId>
  <version>2.0.7</version>
</dependency>

<dependency>
  <groupId>org.pacesys.openstack4j.connectors</groupId>
  <artifactId>openstack4j-httpclient</artifactId>
  <version>2.0.7</version>
</dependency>

**Comment by gondor** [comment]
I'm going to close this for now.  It may be something on your local installation thats not quite compatible.  I've tested on Juno with no issues as well as a cloud provider Rackspace.
