### ISSUE TITLE
NullPointerException on reAuthenticate

### ISSUE THREAD

**Issue by bobybc** [gondor/openstack4j#521]
Hi,
after session/token expiration there is a NPE on re-authenticate :

```
Caused by: ConnectionException{message=while trying to invoke the method org.openstack4j.openstack.identity.domain.v3.KeystoneAuth.unwrap() of a null object returned from org.openstack4j.openstack.identity.domain.v3.KeystoneToken.getCredentials(), status=0}
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:60)
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:32)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:189)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:183)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.get(ServerServiceImpl.java:118)
	... 56 more
Caused by: java.lang.NullPointerException: while trying to invoke the method org.openstack4j.openstack.identity.domain.v3.KeystoneAuth.unwrap() of a null object returned from org.openstack4j.openstack.identity.domain.v3.KeystoneToken.getCredentials()
	at org.openstack4j.openstack.internal.OSAuthenticator.reAuthenticate(OSAuthenticator.java:95)
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:71)
	at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 65 more|
```
Openstack4j version is 2.0.8

Please help me solving it.
10x& best regards
Boby

**Comment by auhlig** [comment]
Hey @bobybc,
I'm on it.

BR

**Comment by auhlig** [comment]
Hi @bobybc,
Should be fixed. 
BR

**Comment by bobybc** [comment]
10x a lot
When it will be released?

**Comment by auhlig** [comment]
Not sure, but I think you should be able to use that now with the 2.10-SNAPSHOT while waiting for the next official release.

**Comment by bobybc** [comment]
No, we need released version
But meanwhile i can test with SNAPSHOT, just to validate the fix
