### ISSUE TITLE
authenticate failed when running openstack4j based project in tomcat6 

### ISSUE THREAD

**Issue by kkxue** [gondor/openstack4j#534]
Hi,gondor:
I'm developping a play framework project which using openstack4j to interactive with openstack rest apis.recently i catch a NoClassDefFoundError  when deploy and running it in tomcat6,
i can sure that the openstack4j*.jar are in the webapps lib directory.
components version:
play: "1.2.5.2"
jdk: "1.7.0_75"
openstack4j: "2.0.0"

thanks for your help!
here is the stacktrace:
```
Execution exception (In /app/controllers/LoginAction.java around line 46)
NoClassDefFoundError occured : Could not initialize class org.openstack4j.connectors.jersey2.ClientFactory

play.exceptions.JavaExecutionException: Could not initialize class org.openstack4j.connectors.jersey2.ClientFactory
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
        at play.server.ServletWrapper$ServletInvocation.execute(ServletWrapper.java:561)
        at play.Invoker$Invocation.run(Invoker.java:278)
        at play.server.ServletWrapper$ServletInvocation.run(ServletWrapper.java:552)
        at play.Invoker.invokeInThread(Invoker.java:68)
        at play.server.ServletWrapper.service(ServletWrapper.java:143)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.openstack4j.connectors.jersey2.ClientFactory
        at org.openstack4j.connectors.jersey2.HttpCommand.initialize(HttpCommand.java:48)
        at org.openstack4j.connectors.jersey2.HttpCommand.create(HttpCommand.java:43)
        at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:53)
        at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
        at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
        at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:77)
        at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:41)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:84)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:65)
        at controllers.LoginAction.os_auth(LoginAction.java:46)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
        ... 18 more
```

**Comment by kkxue** [comment]
it turns out that jar confilcts
