### ISSUE TITLE
V3 reauthentication causes NullPointerException

### ISSUE THREAD

**Issue by petergardfjall** [gondor/openstack4j#574]
I am using Openstack4j 2.0.9 and I have a long-running application that operates against an OpenStack-based cloud provider that uses version 3-style authentication. My application makes use of a small number of OSClient's (one for each thread) which I keep around and reuse for every request (as far as I can understand this is the way to properly make use of Openstack4j [1], please correct me if I'm wrong!).

I've discovered that when Openstack4j attempts to renew its authentication token (in my case after a couple of days, I guess this depends on the particular settings of the OpenStack installation though) it fails with a `NullPointerException` similar to the following:

```
Caused by: java.lang.NullPointerException: null                                                                                                                                            
        at org.openstack4j.openstack.internal.OSAuthenticator.reAuthenticate(OSAuthenticator.java:95) ~[citycloudpool.jar:na]                                                              
        at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:68) ~[citycloudpool.jar:na]                                               
        at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56) ~[citycloudpool.jar:na]                                                      
        at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33) ~[citycloudpool.jar:na]                                                     
        ... 28 common frames omitted                                                                                         
```

I've managed to reproduce the error with the following snippet of code:

```
import org.openstack4j.api.OSClient;
import org.openstack4j.model.common.Identifier;
import org.openstack4j.openstack.OSFactory;
import org.openstack4j.openstack.internal.OSAuthenticator;

public class Reauthenticate {

	public static void main(String[] args) {
		String keystoneUrl = "<URL>";
		String projectId = "<ID>";
		String userId = "<ID>";
		String password = "<ID>";
		String region = "<REGION>";

		OSClient client = OSFactory.builderV3().endpoint(keystoneUrl)
				.credentials(userId, password)
				.scopeToProject(Identifier.byId(projectId),
						Identifier.byId(projectId))
				.authenticate();
		client.useRegion(region);

		System.out.println("Servers:\n" + client.compute().servers().list());

		// Everything works well so far ...

		// THIS is where the a NullPointerException is thrown.
		OSAuthenticator.reAuthenticate();
	}
}
```

The offending statement in `OSAuthenticator` appears to be the `token.getCredentials().unwrap()` in:

```
    authenticateV3((KeystoneAuth) token.getCredentials().unwrap(), info, session.getConfig());
```
[1] http://www.openstack4j.com/learn/threads/

**Comment by petergardfjall** [comment]
I would really like to know also if there is an easy way around this for me without building entirely new `OSClient` instances for every call. I've tried this and that eventually caused the application to run out of memory, which I assume was caused by some internal thread-local state being added for every created `OSClient` instance.

**Comment by auhlig** [comment]
Hey @petergardfjall ,
This is a know error in that version. Please make sure you check out the latest version of OS4j, which curently is 2.10. It should be fixed in that version.

**Comment by petergardfjall** [comment]
Thanks @auhlig!

I didn't even know that `2.10` existed. The home page still mentions `2.0.9` as the latest released version.

**Comment by petergardfjall** [comment]
Closing issue ...
