### ISSUE TITLE
Error when updating Glance image properties using OKHttp

### ISSUE THREAD

**Issue by bsemp** [gondor/openstack4j#597]
When using OKHttp, updating a Glance image properties fails due to a null body in the PUT request.

OKHttp does not accept a null body for PUT and POST requests

```java
Image img = client.images().get(myImageId);
img.getProperties().put("TEST", "A test");
client.images().update(img);
```

    Exception in thread "main" ConnectionException{message=method PUT must have a request body., status=0}
	at org.openstack4j.connectors.okhttp.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.okhttp.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:189)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:183)
	at org.openstack4j.openstack.image.internal.ImageServiceImpl.update(ImageServiceImpl.java:119)
	at test.Test.main(Test.java:75)
    Caused by: java.lang.IllegalArgumentException: method PUT must have a request body.
	at com.squareup.okhttp.Request$Builder.method(Request.java:244)
	at org.openstack4j.connectors.okhttp.HttpCommand.execute(HttpCommand.java:120)
	at org.openstack4j.connectors.okhttp.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.okhttp.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 6 more
Java Result: 1

**Comment by bsemp** [comment]
Please ignore this as it as been already fixed by commit 484c718
