### ISSUE TITLE
Glance API for Version 2

### ISSUE THREAD

**Issue by venkat-cliqr** [gondor/openstack4j#647]
Does the glance api support the V2 api ? I noticed that the BaseImageServices constructor defaults to V1
protected BaseImageServices() {
		super(ServiceType.IMAGE, EnforceVersionToURL.instance("/v1", true));
	}

Is there a way to use V2 version of the api ?

Thanks

**Comment by vinodborole** [comment]
@venkat-cliqr  i do not think the implementation is there for v2 api's for images.

**Comment by emjburns** [comment]
@vinodborole I'll implement this. We want to consume it as well :)

**Comment by olivergondza** [comment]
Hi, Is this resolved after #810? I am asking to know if 3.0.3 is sufficient to resolve https://github.com/jenkinsci/openstack-cloud-plugin/issues/77. Thanks.

**Comment by emjburns** [comment]
@olivergondza should be - http://www.openstack4j.com/learn/image-v2 is where the documentation is.

**Comment by slfletch** [comment]
I am currently trying to use the openstack-cloud plugin and it is sending a GET to v1 when my images are on v2.  Can someone tell me what I need to do in order to get it to work correctly?

**Comment by auhlig** [comment]
Check the service endpoint in the token. Does it contain the correct version?

**Comment by guilhermesteinmuller** [comment]
Hello! I'm using the following groovy script in my jenkins using openstack-cloud-plugin

```
def c = Jenkins.instance.clouds[2].openstack.@clientProvider.get()
println "V1: " + c.images().listAll().size()
println "V2: " + c.imagesV2().list().size()
```
And with the following output

```
V1: 0
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: {"images": [{"container_format": "bare", "min_ram": 0, "updated_at": "2018-08-27T17:37:02Z", "file": "/v2/images/02faa4dc-7e73-402e-a97d-86a076ca5063/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "02faa4dc-7e73-402e-a97d-86a076ca5063", "size": 8589934592, "self": "/v2/images/02faa4dc-7e73-402e-a97d-86a076ca5063", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/02faa4dc-7e73-402e-a97d-86a076ca5063/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "visibility": "public", "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/02faa4dc-7e73-402e-a97d-86a076ca5063/snap", "metadata": {}}], "min_disk": 0, "virtual_size": null, "name": "CentOS 7.5.1804 (x86_64) [2018-06-06]", "checksum": "aa7f819fabfd8c531ab560b30ec4946c", "created_at": "2018-08-27T17:35:17Z", "os_hidden": false, "protected": true, "os_hash_value": "1eac7b24621006ae5c056d9436870c94cfe83a93e696344f52a2eda1d19cf75c1593086c8a6f9399c7058df94847b3a94e36e2545ec221a0aa4f30c501f8bf96"}, {"container_format": "bare", "min_ram": 0, "updated_at": "2018-08-27T17:31:29Z", "file": "/v2/images/3bbfcf36-f4e1-45e2-b970-16d00535942e/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "3bbfcf36-f4e1-45e2-b970-16d00535942e", "size": 2361393152, "self": "/v2/images/3bbfcf36-f4e1-45e2-b970-16d00535942e", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/3bbfcf36-f4e1-45e2-b970-16d00535942e/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "visibility": "public", "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/3bbfcf36-f4e1-45e2-b970-16d00535942e/snap", "metadata": {}}], "min_disk": 0, "virtual_size": null, "name": "Ubuntu 16.04 LTS (x86_64) [2018-08-24]", "checksum": "d135ab2a5195428a07f07f855a4b01c8", "created_at": "2018-08-27T17:30:55Z", "os_hidden": false, "protected": true, "os_hash_value": "46303ca18ac1faa588a68ccd2191061e45a5d1426fd70e1a8cb4b618eeddaabf5cf313fa3db08865cd20f393caf1dc592d91f969f320f7b57ec5508c24556fdf"}, {"container_format": "bare", "min_ram": 0, "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/e21da204-a5ae-4674-9693-bc19ad3de49f/snap", "metadata": {}}], "file": "/v2/images/e21da204-a5ae-4674-9693-bc19ad3de49f/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "e21da204-a5ae-4674-9693-bc19ad3de49f", "size": 6442450944, "os_distro": "fedora-atomic", "self": "/v2/images/e21da204-a5ae-4674-9693-bc19ad3de49f", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/e21da204-a5ae-4674-9693-bc19ad3de49f/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "owner_specified.shade.sha256": "55886dfec0307c0e83871115da6d65503ca95266768860d54c29499ad16fbec5", "updated_at": "2018-08-26T22:57:11Z", "visibility": "public", "owner_specified.shade.object": "images/Fedora Atomic 27 [2018-02-01]", "min_disk": 0, "virtual_size": null, "owner_specified.shade.md5": "63491f6a5289392662ee4809a50f5270", "name": "Fedora Atomic 27 [2018-02-01]", "checksum": "63491f6a5289392662ee4809a50f5270", "created_at": "2018-08-26T22:55:37Z", "os_hidden": false, "protected": false, "os_hash_value": "a43779fe6789c5ea1d5bbaee8916aab91ee224fe5a7fb63c1a54654c532ffd9c38995f33101db4a67fb6218fd2f1cbdddf1da4b2c738e42b75c48c123f94aa7b"}, {"container_format": "bare", "min_ram": 0, "updated_at": "2018-08-26T04:50:32Z", "file": "/v2/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "83d33538-b366-4590-bb0a-a5cd9dbcce6e", "size": 2361393152, "self": "/v2/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "visibility": "public", "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e/snap", "metadata": {}}], "min_disk": 0, "virtual_size": null, "name": "Ubuntu 18.04 LTS (x86_64) [2018-08-23]", "checksum": "78618050983e1731cb1411a2e5104d39", "created_at": "2018-08-26T04:49:58Z", "os_hidden": false, "protected": true, "os_hash_value": "c0e6bde1b4786f92f5053e495444ed150d5d352d1571e5b2352e6a19013ccc5f1a73479052f1be139228fadde2a461ffae08a6441fd7cc30dc04fd7ab76a55e0"}], "schema": "/v2/schemas/images", "first": "/v2/images"}; line: 1, column: 586] (through reference chain: org.openstack4j.openstack.image.v2.domain.Images["images"]->java.util.ArrayList[0]->org.openstack4j.openstack.image.v2.domain.GlanceImage["locations"]->java.util.ArrayList[0])
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:845)
at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:206)
at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:177)
at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:20)
at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1575)
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1200)
at org.openstack4j.connectors.okhttp.HttpResponseImpl.readEntity(HttpResponseImpl.java:122)
Caused: ClientResponseException{message=Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: {"images": [{"container_format": "bare", "min_ram": 0, "updated_at": "2018-08-27T17:37:02Z", "file": "/v2/images/02faa4dc-7e73-402e-a97d-86a076ca5063/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "02faa4dc-7e73-402e-a97d-86a076ca5063", "size": 8589934592, "self": "/v2/images/02faa4dc-7e73-402e-a97d-86a076ca5063", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/02faa4dc-7e73-402e-a97d-86a076ca5063/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "visibility": "public", "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/02faa4dc-7e73-402e-a97d-86a076ca5063/snap", "metadata": {}}], "min_disk": 0, "virtual_size": null, "name": "CentOS 7.5.1804 (x86_64) [2018-06-06]", "checksum": "aa7f819fabfd8c531ab560b30ec4946c", "created_at": "2018-08-27T17:35:17Z", "os_hidden": false, "protected": true, "os_hash_value": "1eac7b24621006ae5c056d9436870c94cfe83a93e696344f52a2eda1d19cf75c1593086c8a6f9399c7058df94847b3a94e36e2545ec221a0aa4f30c501f8bf96"}, {"container_format": "bare", "min_ram": 0, "updated_at": "2018-08-27T17:31:29Z", "file": "/v2/images/3bbfcf36-f4e1-45e2-b970-16d00535942e/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "3bbfcf36-f4e1-45e2-b970-16d00535942e", "size": 2361393152, "self": "/v2/images/3bbfcf36-f4e1-45e2-b970-16d00535942e", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/3bbfcf36-f4e1-45e2-b970-16d00535942e/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "visibility": "public", "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/3bbfcf36-f4e1-45e2-b970-16d00535942e/snap", "metadata": {}}], "min_disk": 0, "virtual_size": null, "name": "Ubuntu 16.04 LTS (x86_64) [2018-08-24]", "checksum": "d135ab2a5195428a07f07f855a4b01c8", "created_at": "2018-08-27T17:30:55Z", "os_hidden": false, "protected": true, "os_hash_value": "46303ca18ac1faa588a68ccd2191061e45a5d1426fd70e1a8cb4b618eeddaabf5cf313fa3db08865cd20f393caf1dc592d91f969f320f7b57ec5508c24556fdf"}, {"container_format": "bare", "min_ram": 0, "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/e21da204-a5ae-4674-9693-bc19ad3de49f/snap", "metadata": {}}], "file": "/v2/images/e21da204-a5ae-4674-9693-bc19ad3de49f/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "e21da204-a5ae-4674-9693-bc19ad3de49f", "size": 6442450944, "os_distro": "fedora-atomic", "self": "/v2/images/e21da204-a5ae-4674-9693-bc19ad3de49f", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/e21da204-a5ae-4674-9693-bc19ad3de49f/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "owner_specified.shade.sha256": "55886dfec0307c0e83871115da6d65503ca95266768860d54c29499ad16fbec5", "updated_at": "2018-08-26T22:57:11Z", "visibility": "public", "owner_specified.shade.object": "images/Fedora Atomic 27 [2018-02-01]", "min_disk": 0, "virtual_size": null, "owner_specified.shade.md5": "63491f6a5289392662ee4809a50f5270", "name": "Fedora Atomic 27 [2018-02-01]", "checksum": "63491f6a5289392662ee4809a50f5270", "created_at": "2018-08-26T22:55:37Z", "os_hidden": false, "protected": false, "os_hash_value": "a43779fe6789c5ea1d5bbaee8916aab91ee224fe5a7fb63c1a54654c532ffd9c38995f33101db4a67fb6218fd2f1cbdddf1da4b2c738e42b75c48c123f94aa7b"}, {"container_format": "bare", "min_ram": 0, "updated_at": "2018-08-26T04:50:32Z", "file": "/v2/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e/file", "owner": "d7594b0298b54bcc9e4e0f252e1da2e4", "id": "83d33538-b366-4590-bb0a-a5cd9dbcce6e", "size": 2361393152, "self": "/v2/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e", "disk_format": "raw", "os_hash_algo": "sha512", "direct_url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e/snap", "schema": "/v2/schemas/image", "status": "active", "tags": [], "visibility": "public", "locations": [{"url": "rbd://ecfa5955-a9b4-4410-a468-c7794a64faf6/images/83d33538-b366-4590-bb0a-a5cd9dbcce6e/snap", "metadata": {}}], "min_disk": 0, "virtual_size": null, "name": "Ubuntu 18.04 LTS (x86_64) [2018-08-23]", "checksum": "78618050983e1731cb1411a2e5104d39", "created_at": "2018-08-26T04:49:58Z", "os_hidden": false, "protected": true, "os_hash_value": "c0e6bde1b4786f92f5053e495444ed150d5d352d1571e5b2352e6a19013ccc5f1a73479052f1be139228fadde2a461ffae08a6441fd7cc30dc04fd7ab76a55e0"}], "schema": "/v2/schemas/images", "first": "/v2/images"}; line: 1, column: 586] (through reference chain: org.openstack4j.openstack.image.v2.domain.Images["images"]->java.util.ArrayList[0]->org.openstack4j.openstack.image.v2.domain.GlanceImage["locations"]->java.util.ArrayList[0]), status=0, status-code=CODE_UNKNOWN}
at org.openstack4j.connectors.okhttp.HttpResponseImpl.readEntity(HttpResponseImpl.java:125)
at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:66)
at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:69)
at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225)
at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207)
at org.openstack4j.openstack.image.v2.internal.ImageServiceImpl.list(ImageServiceImpl.java:45)
at org.openstack4j.api.image.v2.ImageService$list.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
at Script1.run(Script1.groovy:3)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:142)
at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:114)
at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
at hudson.util.RemotingDiagnostics.executeGroovy(RemotingDiagnostics.java:111)
at jenkins.model.Jenkins._doScript(Jenkins.java:4381)
at jenkins.model.Jenkins.doScript(Jenkins.java:4352)
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:530)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Any suggestion if this an issue from openstack-cloud or the v2 implementation in opentack4j?
