### ISSUE TITLE
Version 3 Authentication OpenStack 4j

### ISSUE THREAD

**Issue by huytt1992** [gondor/openstack4j#649]
I am using openstack4j framework  and    I did as instructed http://www.openstack4j.com/learn/getting-started/
but I did get an error.
"step 01
ConnectionException{message=com/fasterxml/jackson/annotation/JsonAutoDetect, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:156)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:78)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:163)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:127)
	at com.inet.dms.openstack4j.OpenStackProvisioning.main(OpenStackProvisioning.java:26)
Caused by: javax.ws.rs.ProcessingException: com/fasterxml/jackson/annotation/JsonAutoDetect
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:233)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:656)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:653)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:653)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:79)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonAutoDetect
	at com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.<clinit>(VisibilityChecker.java:172)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:209)
	at org.openstack4j.core.transport.ObjectMapperSingleton.<init>(ObjectMapperSingleton.java:23)
	at org.openstack4j.core.transport.ObjectMapperSingleton.<clinit>(ObjectMapperSingleton.java:16)
	at org.openstack4j.connectors.jersey2.ClientFactory$CustomContextResolver.getContext(ClientFactory.java:100)
	at org.openstack4j.connectors.jersey2.ClientFactory$CustomContextResolver.getContext(ClientFactory.java:93)
	at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._locateMapperViaProvider(JacksonJsonProvider.java:216)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.locateMapper(ProviderBase.java:830)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:576)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:263)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:500)
	at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:315)
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:227)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
	... 18 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonAutoDetect
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
"
Here is my code
package com.inet.dms.openstack4j;

import java.util.List;

import org.openstack4j.api.OSClient;
import org.openstack4j.model.common.Identifier;
import org.openstack4j.model.identity.User;
import org.openstack4j.openstack.OSFactory;

public class OpenStackProvisioning {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		try {

			System.out.println("step 01");

			OSClient os = OSFactory.builderV3()
                    .endpoint("http://10.60.XXX.XXX:5000/v3")
                    .credentials("admin", "XXXXX", Identifier.byName("default"))
                    .authenticate();

			System.out.println("step 02 :");
			List<? extends User> users = os.identity().users().list();
			System.out.println("step 03");

		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

}

please, help me, thank you !

**Comment by dhague** [comment]
"Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonAutoDetect"
- sounds like a Maven entry might be missing?

**Comment by huytt1992** [comment]
Thank  dhague
I do not use maven, I download and import the library into lib,
now error : 
step 01
ConnectionException{message=java.net.ConnectException: Connection timed out: connect, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:156)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:78)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:163)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:127)
	at com.inet.dms.openstack4j.OpenStackProvisioning.main(OpenStackProvisioning.java:22)
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection timed out: connect
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:229)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:656)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:653)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:653)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:79)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 7 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at org.glassfish.jersey.client.HttpUrlConnector$3.getOutputStream(HttpUrlConnector.java:312)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:200)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:194)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:228)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:1853)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1034)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:607)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:635)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:263)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:500)
	at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:315)
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:227)
	... 19 more

**Comment by vinodborole** [comment]
Please check your openstack endpoint URL connectivity from the box where u are running ur code.

**Comment by luciasarni** [comment]
huytt1992 I´m getting the same errors, how did you fixed it?
